---
AWSTemplateFormatVersion: 2010-09-09

Description: IAM resources for GitHub Actions authorization

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "GitHub integration configuration"
        Parameters:
          - orgName
          - repoName
          - allowAccessFrom
          - envName
          - branchName
    ParameterLabels:
      allowAccessFrom:
        default: "Access Scope"
      orgName:
        default: "GitHub Organization Name"
      repoName:
        default: "GitHub Repository Name"
      envName:
        default: "GitHub Environment Name"
      branchName:
        default: "GitHub Branch Name"

Parameters:
  allowAccessFrom:
    Type: String
    Description: Specifies the scope of access granted to the AWS IAM Role. Choose whether access is limited to a specific branch, environment, or the entire repository.
    AllowedValues:
      - branch      # Access limited to a specific branch
      - environment # Access granted at the environment level
      - repo        # Access granted to the entire repository
  orgName:
    Type: String
    Description: The name of the GitHub organization that owns the repository.
  repoName:
    Type: String
    Description: The name of the GitHub repository for which access is being configured.
  envName:
    Type: String
    Description: The name of the GitHub environment associated with the deployment. Leave empty if not applicable.
    Default: ''
  branchName:
    Type: String
    Description: The name of the GitHub branch for which access is being granted. Leave empty if not applicable.
    Default: ''

Mappings: {}

Conditions:
  allowForBranch:
    Fn::Equals:
      - !Ref allowAccessFrom
      - 'branch'
  allowForEnv:
    Fn::Equals:
      - !Ref allowAccessFrom
      - 'environment'

Resources:
  githubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList: 
        - "sts.amazonaws.com"
      Tags: 
        - Key: Managedby
          Value: cloudformation
        - Key: Name
          Value: GitHub-Integration
      ThumbprintList: 
        - "1c58a3a8518e8759bf075b76b750d4f2df264fcd"
        - "6938fd4d98bab03faadb97b34396831e3780aea1"
      Url: "https://token.actions.githubusercontent.com"

  ghaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::Region}-${orgName}-${repoName}-ghaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !Ref githubOidcProvider
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                Fn::If:
                  - allowForBranch
                  - token.actions.githubusercontent.com:sub: !Sub "repo:${orgName}/${repoName}:ref:refs/heads/${branchName}"
                  - Fn::If:
                    - allowForEnv
                    - token.actions.githubusercontent.com:sub: !Sub "repo:${orgName}/${repoName}:environment:${envName}"
                    - token.actions.githubusercontent.com:sub: !Sub "repo:${orgName}/${repoName}:*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

Outputs:
  ghaRoleArn:
    Description: IAM Role for GitHub Actions runners to assume
    Value: !GetAtt ghaRole.Arn
